config/routes.rb
Rails.application.routes.draw do
  get '/about' => 'static_pages#about' 

  # get '/generate_workout' => 'static_pages#generateWorkout'

  get '/display_workout' => 'static_pages#displayWorkout'

  get '/user_tracking' => 'static_pages#userTracking'
  
  get '/login' => 'sessions#new'
  
  post '/login' => 'sessions#create'
  
  delete '/logout' => 'sessions#destroy'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :workouts, only: [:new, :create, :show, :update]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :account_activations, only: [:edit]
  root "static_pages#home"
end

app/models/workout.rb
class Workout < ApplicationRecord
    # has_many :exercises, through: :users
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  def new
    @workout = Workout.new
  end
  
  def show
    @workout = Workout.find(params[:id])
  end
  
  def create
    @workout = Workout.new(workout_params)
    @user = User.find_by(params[:id])
    @user.inspect
    if @workout.save && @user.valid?
      flash[:info] = "Workout has been generated"
      redirect_to @workout
    else
      flash[:info] = "You are not logged in, this workout will not be saved"
      redirect_to @workout
    end
  end
  
  def update
    @workout = Workout.find(params[:id])
    @user = User.find(session[:user_id])
    @workout.update_attribute(:user_id, @user.id)
    redirect_to @user
  end
  
  private
  def workout_params
    params.require(:workout).permit(:category, 
                                    :intensity_level, 
                                    :time)
  end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/new.html.erb
<h1>Generate Workout</h1>

<p>Choose your workout specifications here:</p>
<div class="background">
  <%= form_for(@workout) do |w| %>
  <%= w.label :category %>
  <%= w.select :category, [['WeightLifting','WeightLifting'],['Cardio','Cardio'],['Yoga','Yoga']] %>
  
  <%= w.label :intensity_level%>
  <%= w.select :intensity_level, [['Low', 1], ['Medium', 2], ['High', 3]] %>
  
  <%= w.label :time %>
  <%= w.text_field :time %>
  
  <%= w.submit 'Generate', class: "btn btn-primary btn-xs" %>
<% end %>
</div>

app/views/workouts/show.html.erb
<% require 'sqlite3' %>
<div class="background">
  <h2 class="workout">You chose:<h2>
  <% remaining = 0 %>
  <% db = SQLite3::Database.open( "db/development.sqlite3" ) %>
  
  <% db.execute( "SELECT * FROM workouts WHERE id = #{params[:id]}" ) do |row| %>
    <h4 class="workout">Category: <%= row[3] %></h4>
    <h4 class="workout">Intensity: <%= row[4] %></h4>
    <h4 class="workout">Time: <%= row[5] %></h4>
    <% remaining = row[5].to_i %>
  <% end %>
  
  <% db.execute( "SELECT name, intensity_level, time, link_to_exercise
                  FROM exercises 
                  WHERE category = (SELECT category FROM workouts 
                                    WHERE id = #{params[:id]}) 
                  AND intensity_level = (SELECT intensity_level FROM workouts
                                         WHERE id = #{params[:id]})" ) do |row| %>
     
    <% if remaining - row[2] < 0 %>
    <% else %>
      <% remaining = remaining - row[2] %>
      <div class="exercise">
        <h4 class="workout"><%= "Exercise: " + row[0] %></h4>
        <h5 class="workout"><%= "Minutes: " + row[2].to_s %></h5>
        <h5 class="workout"><%= "How to do this Exercise: " %> 
                            <%= link_to "#{row[3]}", "#{row[3]}", class: "links", target: '_blank' %></h5>
      </div>
    <% end %>
  <% end %>
  
  
  <%= link_to 'Re-Generate', new_workout_path, id: 'slide', class: "btn btn-primary" %>
  <% if logged_in? %>
    <%= form_for(@workout, url: workout_path(params[:id])) do |w| %>
      <%= hidden_field_tag :id, @workout.id %>
      <% puts @workout.id %>
      <%= w.submit 'Save Workout', id: 'slide', class: "btn btn-primary" %>
    <% end %>
  <% end %>
</div>