config/routes.rb
Rails.application.routes.draw do
  get '/about' => 'static_pages#about' 

  # get '/generate_workout' => 'static_pages#generateWorkout'

  get '/display_workout' => 'static_pages#displayWorkout'

  get '/user_tracking' => 'static_pages#userTracking'
  
  get '/login' => 'sessions#new'
  
  post '/login' => 'sessions#create'
  
  delete '/logout' => 'sessions#destroy'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :workouts, only: [:new, :create, :show, :update]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :account_activations, only: [:edit]
  root "static_pages#home"
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token
  before_create :create_activation_digest
  before_save :downcase_email
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true
  
  class << self
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end
    
    def new_token
      SecureRandom.urlsafe_base64
    end
  end
    
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end
  
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end
  
  private
  
  def downcase_email
    self.email = email.downcase
  end
  
  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  
  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.account_activation(@user).deliver_now
      flash[:info] = 'Please check your email to activate your account'
      redirect_to root_url
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def reset_password
    @user = User.find_by(email: params[:email])
    if @user
      UserMailer.password_reset(@user).deliver_now
      flash.now[:info] = 'Please check email for password reset link'
      redirect_to root_url
    else
      flash.now[:danger] = "Can't find user with that email address"
      render 'new'
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = 'Profile updated'
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = 'User deleted'
    redirect_to root_url
  end
  
  private

  def user_params
    params.require(:user).permit(:name, 
                                 :email, 
                                 :password,
                                 :password_confirmation)
  end
    
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = 'Please log in.'
      redirect_to login_url
    end
  end
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/users_helper.rb
#Users Helper module
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), id: 'session', class: "btn btn-primary" %>
<% end %>

 

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save Changes') %>
<h1>Update your profile</h1>
<%= link_to "Delete Profile", user_path, method: :delete, class: 'btn btn-primary right' %>
<div class="row">
  <div class="col-md-12">
    <div class="background">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my Account') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-12">
    <div class="background">
      <%= render 'form' %>      
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h2 class="workout"><%= @user.name %>'s Profile</h2><br />
<% if current_user == @user %>
    <%= link_to "Edit Profile", edit_user_path(current_user), class: 'btn btn-primary' %>
    
<% end %>
<div class="background">
  <h2 class="workout">Workout Log</h2>
  <br />
  <% if !Workout.find_by(user_id: params[:id]).nil? %>
    <% db = SQLite3::Database.open( "db/development.sqlite3" ) %>
    <table>
      <tr>
        <th class="workoutTable tableHeader">Category</th>
        <th class="workoutTable tableHeader">Intensity</th>
        <th class="workoutTable tableHeader">Time</th>
      </tr>
      <% db.execute( "SELECT * FROM workouts 
                      WHERE user_id = #{params[:id]}
                      ORDER BY created_at DESC LIMIT 10" ) do |row| %>
        <tr>
          <td class="workoutTable"><%= row[3] %></td>
          <td class="workoutTable"><%= row[4] %></td>
          <td class="workoutTable"><%= row[5] %></td>
        </tr>
      <% end %>
      
      
      <tr>
        <td></td>
        <td class="workoutTable center">Summary Data</td>
        <td></td>
      </tr>
      <tr>
        <td class="workoutTable summary">
          <% db.execute( "SELECT category, count(category) FROM workouts 
                          WHERE user_id = #{params[:id]} 
                          GROUP BY category
                          ORDER BY count(category) DESC LIMIT 1" ) do |row| %>
          <%= "Favorite Category: " + row[0] %>
          <% end %>
        </td>
        <td class="workoutTable summary">
          <% db.execute( "SELECT sum(intensity_level), count(intensity_level) FROM workouts 
                          WHERE user_id = #{params[:id]}" ) do |row| %>
          <%= "Average Intensity: " + '%.2f' % (row[0].to_f / row[1].to_f).to_s %>
          <% end %>
        </td>
        <td class="workoutTable summary">
          <% db.execute( "SELECT sum(time), count(time) FROM workouts 
                          WHERE user_id = #{params[:id]}") do |row| %>
          <%= "Average Time: " + (row[0] / row[1]).to_s + " Min(s)" %>
          <% end %>
        </td>
      </tr>
      <tr>
        <% d = DateTime.now %>
        <td class="workoutTable summary">
          <% db.execute( "SELECT count(created_at) FROM workouts 
                          WHERE user_id = #{params[:id]} AND created_at LIKE '%#{d.strftime("%m")}%'") do |row| %>
          <%= "Workouts this month: " + row[0].to_s %>
          <% end %>
        </td>
        <td class="workoutTable summary">
          <% db.execute( "SELECT strftime('%d','now'), count(created_at) FROM workouts 
                          WHERE user_id = #{params[:id]}") do |row| %>
          <%= "Percentage of Days: " + '%.1f' % ((row[1].to_f / row[0].to_f) * 100).to_s + '%' %>
          <% end %>
        </td>
        <td class="workoutTable summary">
          <% db.execute( "SELECT strftime('%d','now'), count(created_at) FROM workouts 
                          WHERE user_id = #{params[:id]}") do |row| %>
          <%= "Workouts needed for 100%: " + (row[0].to_i - row[1]).to_s %>
          <% end %>
        </td>
      </tr>
    </table>
  <% else %>
    <p>You must <%= link_to "Generate", new_workout_path, class: 'btn btn-primary' %> a workout in order to see your workout log.</p>
  <% end %>
</div>