config/routes.rb
Rails.application.routes.draw do
  get '/about' => 'static_pages#about' 

  # get '/generate_workout' => 'static_pages#generateWorkout'

  get '/display_workout' => 'static_pages#displayWorkout'

  get '/user_tracking' => 'static_pages#userTracking'
  
  get '/login' => 'sessions#new'
  
  post '/login' => 'sessions#create'
  
  delete '/logout' => 'sessions#destroy'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :workouts, only: [:new, :create, :show, :update]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :account_activations, only: [:edit]
  root "static_pages#home"
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="navbar-header">

    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
    </button>
    <%= link_to "DC", root_path, class: "navbar-brand" %>
  </div>

  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li class="active">
        <%= link_to "Home", root_path %>
      </li>
      <li>
        <%= link_to "About", about_path %>
      </li>
      <li>
        <%= link_to "Generate Workout", new_workout_path %>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if logged_in? %>
        <li>
          <%= link_to "Profile", current_user %>
        </li>
        <li>
          <%= link_to "Log-out", logout_path, method: :delete %>
        </li>
        
      <% else %>
        <li>
          <%= link_to "Log-in", login_path %>
        </li>
        <li>
          <%= link_to "Sign-up", new_user_path %>
        </li>
      <% end %>
    </ul>
  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DC Fitness Institute</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    </div>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>